In [1]:
import pandas as pd
import numpy as np

In [2]:
forex_data = pd.read_csv("Signal_Data/forex_with_signals.csv")

forex_data.head()

,DateTime,PairID,PairName,Open,High,Low,Close,Volume,Spread,SMA_10,SMA_20,EMA_10,RSI,MACD,Signal_Line,Middle_Band,Upper_Band,Lower_Band,Signal
0,2023-01-01 00:00:00,1,EUR/USD,1.08103,1.08103,1.08019,1.08054,2651,0.9,NaN,NaN,1.080540,NaN,0.000000,0.000000,NaN,NaN,NaN,HOLD
1,2023-01-01 01:00:00,1,EUR/USD,1.08010,1.08043,1.07974,1.08028,2292,1.0,NaN,NaN,1.080493,NaN,-0.000021,-0.000004,NaN,NaN,NaN,HOLD
2,2023-01-01 02:00:00,1,EUR/USD,1.08036,1.08158,1.07961,1.08054,1796,1.2,NaN,NaN,1.080501,NaN,-0.000016,-0.000007,NaN,NaN,NaN,HOLD
3,2023-01-01 03:00:00,1,EUR/USD,1.08068,1.08126,1.07973,1.08088,4019,1.4,NaN,NaN,1.080570,NaN,0.000015,-0.000002,NaN,NaN,NaN,HOLD
4,2023-01-01 04:00:00,1,EUR/USD,1.08042,1.08042,1.07967,1.08030,2207,1.6,NaN,NaN,1.080521,NaN,-0.000007,-0.000003,NaN,NaN,NaN,HOLD

In [3]:
print(forex_data.shape)

(500, 19)

In [4]:
print(forex_data.columns)

Index(['DateTime', 'PairID', 'PairName', 'Open', 'High', 'Low', 'Close',
       'Volume', 'Spread', 'SMA_10', 'SMA_20', 'EMA_10', 'RSI', 'MACD',
       'Signal_Line', 'Middle_Band', 'Upper_Band', 'Lower_Band', 'Signal'],
      dtype='str')

In [5]:
def trading_ai(signal):
    if signal == "BUY":
        return "🟢 AI Recommendation: BUY"

    elif signal == "SELL":
        return "🔴 AI Recommendation: SELL"

    else:
        return "🟡 AI Recommendation: HOLD"

In [6]:
forex_data["AI_Recommendation"] = forex_data["Signal"].apply(trading_ai)

forex_data[
    ["DateTime", "Close", "Signal", "AI_Recommendation"]
].head(20)

               DateTime    Close Signal          AI_Recommendation
0   2023-01-01 00:00:00  1.08054   HOLD  🟡 AI Recommendation: HOLD
1   2023-01-01 01:00:00  1.08028   HOLD  🟡 AI Recommendation: HOLD
2   2023-01-01 02:00:00  1.08054   HOLD  🟡 AI Recommendation: HOLD
3   2023-01-01 03:00:00  1.08088   HOLD  🟡 AI Recommendation: HOLD
4   2023-01-01 04:00:00  1.08030   HOLD  🟡 AI Recommendation: HOLD
5   2023-01-01 05:00:00  1.07998   HOLD  🟡 AI Recommendation: HOLD
6   2023-01-01 06:00:00  1.08087   HOLD  🟡 AI Recommendation: HOLD
7   2023-01-01 07:00:00  1.08108   HOLD  🟡 AI Recommendation: HOLD
8   2023-01-01 08:00:00  1.08058   HOLD  🟡 AI Recommendation: HOLD
9   2023-01-01 09:00:00  1.08017   HOLD  🟡 AI Recommendation: HOLD
10  2023-01-01 10:00:00  1.07926   HOLD  🟡 AI Recommendation: HOLD
11  2023-01-01 11:00:00  1.07906   HOLD  🟡 AI Recommendation: HOLD
12  2023-01-01 12:00:00  1.07945   HOLD  🟡 AI Recommendation: HOLD
13  2023-01-01 13:00:00  1.08114   HOLD  🟡 AI Recommendation: HOLD
14  2023-01-01 14:00:00  1.08090   HOLD  🟡 AI Recommendation: HOLD
15  2023-01-01 15:00:00  1.08036   HOLD  🟡 AI Recommendation: HOLD
16  2023-01-01 16:00:00  1.08047   HOLD  🟡 AI Recommendation: HOLD
17  2023-01-01 17:00:00  1.07888   HOLD  🟡 AI Recommendation: HOLD
18  2023-01-01 18:00:00  1.07871   HOLD  🟡 AI Recommendation: HOLD
19  2023-01-01 19:00:00  1.07863   SELL  🔴 AI Recommendation: SELL

In [7]:
print(forex_data["AI_Recommendation"].value_counts())

AI_Recommendation
🟡 AI Recommendation: HOLD    242
🟢 AI Recommendation: BUY     155
🔴 AI Recommendation: SELL    103
Name: count, dtype: int64

In [8]:
import os

os.makedirs("Final_AI_Output", exist_ok=True)

forex_data.to_csv(
    "Final_AI_Output/final_ai_predictions.csv",
    index=False
)

In [9]:
import os

print(os.listdir("Final_AI_Output"))

['final_ai_predictions.csv']

In [10]:
forex_data.tail(10)

,DateTime,PairID,PairName,Open,High,Low,Close,Volume,Spread,SMA_10,SMA_20,EMA_10,RSI,MACD,Signal_Line,Middle_Band,Upper_Band,Lower_Band,Signal,AI_Recommendation
490,2023-01-21 10:00:00,1,EUR/USD,1.11358,1.11437,1.11314,1.11329,2908,1.7,1.113828,1.115434,1.113941,24.740933,-0.000206,0.000282,1.115434,1.119296,1.111571,HOLD,🟡 AI Recommendation: HOLD
491,2023-01-21 11:00:00,1,EUR/USD,1.11159,1.11358,1.11091,1.11173,5003,1.8,1.113401,1.115252,1.113539,15.963512,-0.000380,0.000149,1.115252,1.119455,1.111049,HOLD,🟡 AI Recommendation: HOLD
492,2023-01-21 12:00:00,1,EUR/USD,1.10974,1.11035,1.10897,1.10983,2639,1.9,1.112842,1.114955,1.112864,9.472656,-0.000664,-0.000013,1.114955,1.119795,1.110115,HOLD,🟡 AI Recommendation: HOLD
493,2023-01-21 13:00:00,1,EUR/USD,1.10938,1.10965,1.10881,1.10950,11411,1.6,1.112423,1.114634,1.112253,9.317963,-0.000905,-0.000192,1.114634,1.120026,1.109243,HOLD,🟡 AI Recommendation: HOLD
494,2023-01-21 14:00:00,1,EUR/USD,1.10944,1.11067,1.10901,1.10983,3322,1.0,1.112091,1.114221,1.111812,13.727561,-0.001058,-0.000365,1.114221,1.119760,1.108682,HOLD,🟡 AI Recommendation: HOLD
495,2023-01-21 15:00:00,1,EUR/USD,1.10876,1.10912,1.10822,1.10861,2403,1.1,1.111617,1.113773,1.111230,13.013013,-0.001262,-0.000544,1.113773,1.119614,1.107933,HOLD,🟡 AI Recommendation: HOLD
496,2023-01-21 16:00:00,1,EUR/USD,1.10722,1.10751,1.10671,1.10739,2081,1.5,1.111024,1.113284,1.110532,12.229539,-0.001505,-0.000737,1.113284,1.119546,1.107021,HOLD,🟡 AI Recommendation: HOLD
497,2023-01-21 17:00:00,1,EUR/USD,1.10730,1.10735,1.10687,1.10713,1828,1.1,1.110372,1.112755,1.109913,14.192140,-0.001700,-0.000929,1.112755,1.119229,1.106281,HOLD,🟡 AI Recommendation: HOLD
498,2023-01-21 18:00:00,1,EUR/USD,1.10729,1.10775,1.10712,1.10758,3894,1.7,1.109774,1.112227,1.109489,19.294377,-0.001796,-0.001103,1.112227,1.118576,1.105879,HOLD,🟡 AI Recommendation: HOLD
499,2023-01-21 19:00:00,1,EUR/USD,1.10871,1.10902,1.10829,1.10895,2615,1.4,1.109384,1.111777,1.109391,28.515625,-0.001742,-0.001231,1.111777,1.117672,1.105881,HOLD,🟡 AI Recommendation: HOLD